# Copyright 2025 Perfana Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a basic workflow that is manually triggered

name: Build perfana-snapshot snapshot image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

jobs:
  build_snapshot_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from code branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install git-tag-version
        run: |
          sudo npm install -g git-tag-version
      - name: Get tag
        run: |
          echo 'TAG_NAME<<EOF' >> $GITHUB_ENV
          git-tag-version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Write tag to file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "version.txt"
          FILE_DATA: "${{ env.TAG_NAME }}"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: |
          echo ${{ env.TAG_NAME }}-${{ github.sha }}
          docker buildx build --platform linux/amd64,linux/arm64 --push  -t perfana/perfana-snapshot-test:${{ env.TAG_NAME }}-${{ github.sha }} .
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: perfana/perfana-snapshot-test:${{ env.TAG_NAME }}-${{ github.sha }}
          args: --severity-threshold=high --app-vulns

      #      - name: Push the tagged Docker image
      #        run: docker push perfana/perfana-snapshot-test:${{ env.TAG_NAME }}-${{ github.sha }}

     